name: dto_generator
description: A Dart package that generates Data Transfer Object (DTO) classes from OpenAPI/Swagger specifications
version: 1.0.5
repository: https://github.com/stasinato/dto_generator

environment:
  sdk: ^3.5.4

dependencies:
  yaml: ^3.1.2
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.1.1

executables:
  dto_generator: dto_generator
