name: dto_generator
version: 0.0.1
description: A tool to generate DTO classes from Swagger/OpenAPI definitions.
homepage: https://github.com/stasinato/dto_generator
repository: https://github.com/stasinato/dto_generator
environment:
  sdk: ">=3.0.0"

dependencies:
  json_annotation: ^4.9.0
  yaml: ^3.1.3

dev_dependencies:
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  test: ^1.25.15

executables:
  dto_generator: bin/dto_generator.dart
